#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BazaDanych")]
public partial class BazaDanychDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertUzytkownik(Uzytkownik instance);
  partial void UpdateUzytkownik(Uzytkownik instance);
  partial void DeleteUzytkownik(Uzytkownik instance);
  partial void InsertTabDosw(TabDosw instance);
  partial void UpdateTabDosw(TabDosw instance);
  partial void DeleteTabDosw(TabDosw instance);
  partial void InsertPrzeciwnik(Przeciwnik instance);
  partial void UpdatePrzeciwnik(Przeciwnik instance);
  partial void DeletePrzeciwnik(Przeciwnik instance);
  #endregion
	
	public BazaDanychDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BazaDanychConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public BazaDanychDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BazaDanychDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BazaDanychDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BazaDanychDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Uzytkownik> Uzytkowniks
	{
		get
		{
			return this.GetTable<Uzytkownik>();
		}
	}
	
	public System.Data.Linq.Table<TabDosw> TabDosws
	{
		get
		{
			return this.GetTable<TabDosw>();
		}
	}
	
	public System.Data.Linq.Table<Przeciwnik> Przeciwniks
	{
		get
		{
			return this.GetTable<Przeciwnik>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Uzytkownik")]
public partial class Uzytkownik : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Login;
	
	private string _Haslo;
	
	private string _Email;
	
	private int _Poziom;
	
	private int _Doswiadczenie;
	
	private int _Sila;
	
	private int _Szybkosc;
	
	private int _Wytrzymalosc;
	
	private System.Nullable<int> _Zloto;
	
	private System.Nullable<bool> _CzyAktywny;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    partial void OnHasloChanging(string value);
    partial void OnHasloChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPoziomChanging(int value);
    partial void OnPoziomChanged();
    partial void OnDoswiadczenieChanging(int value);
    partial void OnDoswiadczenieChanged();
    partial void OnSilaChanging(int value);
    partial void OnSilaChanged();
    partial void OnSzybkoscChanging(int value);
    partial void OnSzybkoscChanged();
    partial void OnWytrzymaloscChanging(int value);
    partial void OnWytrzymaloscChanged();
    partial void OnZlotoChanging(System.Nullable<int> value);
    partial void OnZlotoChanged();
    partial void OnCzyAktywnyChanging(System.Nullable<bool> value);
    partial void OnCzyAktywnyChanged();
    #endregion
	
	public Uzytkownik()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="NVarChar(50)")]
	public string Login
	{
		get
		{
			return this._Login;
		}
		set
		{
			if ((this._Login != value))
			{
				this.OnLoginChanging(value);
				this.SendPropertyChanging();
				this._Login = value;
				this.SendPropertyChanged("Login");
				this.OnLoginChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Haslo", DbType="NVarChar(50)")]
	public string Haslo
	{
		get
		{
			return this._Haslo;
		}
		set
		{
			if ((this._Haslo != value))
			{
				this.OnHasloChanging(value);
				this.SendPropertyChanging();
				this._Haslo = value;
				this.SendPropertyChanged("Haslo");
				this.OnHasloChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Poziom", DbType="Int NOT NULL")]
	public int Poziom
	{
		get
		{
			return this._Poziom;
		}
		set
		{
			if ((this._Poziom != value))
			{
				this.OnPoziomChanging(value);
				this.SendPropertyChanging();
				this._Poziom = value;
				this.SendPropertyChanged("Poziom");
				this.OnPoziomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doswiadczenie", DbType="Int NOT NULL")]
	public int Doswiadczenie
	{
		get
		{
			return this._Doswiadczenie;
		}
		set
		{
			if ((this._Doswiadczenie != value))
			{
				this.OnDoswiadczenieChanging(value);
				this.SendPropertyChanging();
				this._Doswiadczenie = value;
				this.SendPropertyChanged("Doswiadczenie");
				this.OnDoswiadczenieChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sila", DbType="Int NOT NULL")]
	public int Sila
	{
		get
		{
			return this._Sila;
		}
		set
		{
			if ((this._Sila != value))
			{
				this.OnSilaChanging(value);
				this.SendPropertyChanging();
				this._Sila = value;
				this.SendPropertyChanged("Sila");
				this.OnSilaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Szybkosc", DbType="Int NOT NULL")]
	public int Szybkosc
	{
		get
		{
			return this._Szybkosc;
		}
		set
		{
			if ((this._Szybkosc != value))
			{
				this.OnSzybkoscChanging(value);
				this.SendPropertyChanging();
				this._Szybkosc = value;
				this.SendPropertyChanged("Szybkosc");
				this.OnSzybkoscChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wytrzymalosc", DbType="Int NOT NULL")]
	public int Wytrzymalosc
	{
		get
		{
			return this._Wytrzymalosc;
		}
		set
		{
			if ((this._Wytrzymalosc != value))
			{
				this.OnWytrzymaloscChanging(value);
				this.SendPropertyChanging();
				this._Wytrzymalosc = value;
				this.SendPropertyChanged("Wytrzymalosc");
				this.OnWytrzymaloscChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zloto", DbType="Int")]
	public System.Nullable<int> Zloto
	{
		get
		{
			return this._Zloto;
		}
		set
		{
			if ((this._Zloto != value))
			{
				this.OnZlotoChanging(value);
				this.SendPropertyChanging();
				this._Zloto = value;
				this.SendPropertyChanged("Zloto");
				this.OnZlotoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CzyAktywny", DbType="Bit")]
	public System.Nullable<bool> CzyAktywny
	{
		get
		{
			return this._CzyAktywny;
		}
		set
		{
			if ((this._CzyAktywny != value))
			{
				this.OnCzyAktywnyChanging(value);
				this.SendPropertyChanging();
				this._CzyAktywny = value;
				this.SendPropertyChanged("CzyAktywny");
				this.OnCzyAktywnyChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TabDosw")]
public partial class TabDosw : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Poziom;
	
	private System.Nullable<int> _MinDosw;
	
	private int _MaxDosw;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPoziomChanging(int value);
    partial void OnPoziomChanged();
    partial void OnMinDoswChanging(System.Nullable<int> value);
    partial void OnMinDoswChanged();
    partial void OnMaxDoswChanging(int value);
    partial void OnMaxDoswChanged();
    #endregion
	
	public TabDosw()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Poziom", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Poziom
	{
		get
		{
			return this._Poziom;
		}
		set
		{
			if ((this._Poziom != value))
			{
				this.OnPoziomChanging(value);
				this.SendPropertyChanging();
				this._Poziom = value;
				this.SendPropertyChanged("Poziom");
				this.OnPoziomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinDosw", DbType="Int")]
	public System.Nullable<int> MinDosw
	{
		get
		{
			return this._MinDosw;
		}
		set
		{
			if ((this._MinDosw != value))
			{
				this.OnMinDoswChanging(value);
				this.SendPropertyChanging();
				this._MinDosw = value;
				this.SendPropertyChanged("MinDosw");
				this.OnMinDoswChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxDosw", DbType="Int NOT NULL")]
	public int MaxDosw
	{
		get
		{
			return this._MaxDosw;
		}
		set
		{
			if ((this._MaxDosw != value))
			{
				this.OnMaxDoswChanging(value);
				this.SendPropertyChanging();
				this._MaxDosw = value;
				this.SendPropertyChanged("MaxDosw");
				this.OnMaxDoswChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Przeciwnik")]
public partial class Przeciwnik : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Nazwa;
	
	private int _Poziom;
	
	private int _DaDosw;
	
	private int _DaZlot;
	
	private int _Sila;
	
	private int _Szybkosc;
	
	private int _Wytrzymalosc;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNazwaChanging(string value);
    partial void OnNazwaChanged();
    partial void OnPoziomChanging(int value);
    partial void OnPoziomChanged();
    partial void OnDaDoswChanging(int value);
    partial void OnDaDoswChanged();
    partial void OnDaZlotChanging(int value);
    partial void OnDaZlotChanged();
    partial void OnSilaChanging(int value);
    partial void OnSilaChanged();
    partial void OnSzybkoscChanging(int value);
    partial void OnSzybkoscChanged();
    partial void OnWytrzymaloscChanging(int value);
    partial void OnWytrzymaloscChanged();
    #endregion
	
	public Przeciwnik()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Nazwa
	{
		get
		{
			return this._Nazwa;
		}
		set
		{
			if ((this._Nazwa != value))
			{
				this.OnNazwaChanging(value);
				this.SendPropertyChanging();
				this._Nazwa = value;
				this.SendPropertyChanged("Nazwa");
				this.OnNazwaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Poziom", DbType="Int NOT NULL")]
	public int Poziom
	{
		get
		{
			return this._Poziom;
		}
		set
		{
			if ((this._Poziom != value))
			{
				this.OnPoziomChanging(value);
				this.SendPropertyChanging();
				this._Poziom = value;
				this.SendPropertyChanged("Poziom");
				this.OnPoziomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaDosw", DbType="Int NOT NULL")]
	public int DaDosw
	{
		get
		{
			return this._DaDosw;
		}
		set
		{
			if ((this._DaDosw != value))
			{
				this.OnDaDoswChanging(value);
				this.SendPropertyChanging();
				this._DaDosw = value;
				this.SendPropertyChanged("DaDosw");
				this.OnDaDoswChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaZlot", DbType="Int NOT NULL")]
	public int DaZlot
	{
		get
		{
			return this._DaZlot;
		}
		set
		{
			if ((this._DaZlot != value))
			{
				this.OnDaZlotChanging(value);
				this.SendPropertyChanging();
				this._DaZlot = value;
				this.SendPropertyChanged("DaZlot");
				this.OnDaZlotChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sila", DbType="Int NOT NULL")]
	public int Sila
	{
		get
		{
			return this._Sila;
		}
		set
		{
			if ((this._Sila != value))
			{
				this.OnSilaChanging(value);
				this.SendPropertyChanging();
				this._Sila = value;
				this.SendPropertyChanged("Sila");
				this.OnSilaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Szybkosc", DbType="Int NOT NULL")]
	public int Szybkosc
	{
		get
		{
			return this._Szybkosc;
		}
		set
		{
			if ((this._Szybkosc != value))
			{
				this.OnSzybkoscChanging(value);
				this.SendPropertyChanging();
				this._Szybkosc = value;
				this.SendPropertyChanged("Szybkosc");
				this.OnSzybkoscChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wytrzymalosc", DbType="Int NOT NULL")]
	public int Wytrzymalosc
	{
		get
		{
			return this._Wytrzymalosc;
		}
		set
		{
			if ((this._Wytrzymalosc != value))
			{
				this.OnWytrzymaloscChanging(value);
				this.SendPropertyChanging();
				this._Wytrzymalosc = value;
				this.SendPropertyChanged("Wytrzymalosc");
				this.OnWytrzymaloscChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
